name: crypto_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author:
homepage:

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  zilliqa_api:
    path: ../zilliqa_api
  blockchain_interface:
    path: ../blockchain_interface
  
dev_dependencies:
  flutter_test:
    sdk: flutter
